# This is a basic workflow to help you get started with Actions

name: SSH Server

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo useradd -m -s /bin/bash hudacihuyy
          echo 'hudacihuyy:ll' | sudo chpasswd
          sudo usermod -aG sudo hudacihuyy
          echo "User 'hudacihuyy' dibuat."

      - name: Jalankan perintah sebagai user baru
        run: |
          sudo -u hudacihuyy bash -c 'echo "Hello dari user $(whoami)"'
          
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
