name: SSH Server
on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
          path: temp-repo  
      
      - name: Create User
        run: |
          sudo useradd -m -s /bin/bash hudacihuyy
          echo 'hudacihuyy:ll' | sudo chpasswd
          sudo usermod -aG sudo hudacihuyy
          echo "hudacihuyy ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/hudacihuyy

      - name: Move repo contents to /home/hudacihuyy
        run: |
          sudo cp -r temp-repo/. /home/hudacihuyy/
          sudo chown -R hudacihuyy:hudacihuyy /home/hudacihuyy

      - name: Start Ssh snd Minecraft Server
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PLAYITAUTHKEY }} 
        run: |
          sudo -u hudacihuyy bash -c 'echo "Hello dari user $(whoami)"'
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install playit
          echo -e "Port 22\nListenAddress 0.0.0.0" | sudo tee /etc/ssh/sshd_config
          sudo ssh-keygen -A
          sudo mkdir -p /run/sshd
          sudo chmod 755 /run/sshd
          sudo /usr/sbin/sshd
          sudo apt remove --purge '*jdk*' '*jre*' '*java*'
          sudo apt install curl gnupg -y
          curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor | sudo tee /usr/share/keyrings/azul.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | sudo tee /etc/apt/sources.list.d/zulu.list
          sudo apt update
          sudo apt install zulu21-jdk
          git clone https://github.com/Mafatikhul281/SSH-Github-Actions.git .
          cd spigot-server
          java -Xmx2G -Xms1G -jar spigot-1.21.5.jar

      - name: Run playit
        run: playit --secret $PLAYIT_AUTH_KEY
      
      - name: Add sleep
        run: |
          sleep 6h
