####### This is a basic workflow to help you get started with Actions

name: SSH Server

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Buat User
        run: |
          sudo useradd -m -s /bin/bash hudacihuyy
          echo 'hudacihuyy:ll' | sudo chpasswd
          sudo usermod -aG sudo hudacihuyy
          echo "hudacihuyy ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/hudacihuyy
          echo "User 'hudacihuyy' dibuat."

      - name: Start Ssh
        run: |
          sudo -u hudacihuyy bash -c 'echo "Hello dari user $(whoami)"'
          sudo apt update
          sudo apt install openssh-server
          echo "Port 22" | sudo tee /etc/ssh/sshd_config
          echo "ListenAddress 0.0.0.0" | sudo tee /etc/ssh/sshd_config
          sudo ssh-keygen -A
				sudo mkdir -p /run/sshd
				sudo chmod 755 /run/sshd
          sudo /usr/sbin/sshd
          curl icanhazip.com
          

      # Runs a set of commands using the runners shell
      - name: Add sleep
        run: |
          sleep 6h
