name: SSH Server
on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create User
        run: |
          sudo useradd -m -s /bin/bash hudacihuyy
          echo 'hudacihuyy:ll' | sudo chpasswd
          sudo usermod -aG sudo hudacihuyy
          echo "hudacihuyy ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/hudacihuyy
          echo "User 'hudacihuyy' dibuat."

      - name: Start Ssh
        run: |
          sudo -u hudacihuyy bash -c 'echo "Hello dari user $(whoami)"'
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install playit
          echo "Port 22" | sudo tee /etc/ssh/sshd_config
          echo "ListenAddress 0.0.0.0" | sudo tee /etc/ssh/sshd_config
          sudo ssh-keygen -A
          sudo mkdir -p /run/sshd
          sudo chmod 755 /run/sshd
          sudo /usr/sbin/sshd
          playit --secret dac598d8458c722d1c7d1e322c20c9a89fd77431cd2ca72ce4616d0e7a28ade2
          
      - name: Add sleep
        run: |
          sleep 6h
